name: SAP Cloud Integration - Download IFlow Test

on:
  workflow_dispatch:
    inputs:
      PackageID:
        description: "PackageID you want to download"
        required: true

permissions:
  contents: write

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Für Push-Berechtigung

      - name: Fetch OAuth Token
        id: fetch-token
        run: |
          TOKEN_RESPONSE=$(curl -s -X POST \
            -u "${{ secrets.CLIENT_ID }}:${{ secrets.CLIENT_SECRET }}" \
            -d "grant_type=client_credentials" \
            "https://ntt-pi-dev.authentication.eu10.hana.ondemand.com/oauth/token")
          ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.access_token')
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Download SAP CPI Package as ZIP
        run: |
          curl -s -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            -o package.zip \
            "https://ntt-pi-dev.it-cpi001.cfapps.eu10.hana.ondemand.com/api/v1/IntegrationPackages('${{ github.event.inputs.PACKAGEID}}')/\$value"

      - name: Move ZIP to Repository Folder
        run: |
          mkdir -p sap-packages  # Ordner erstellen, falls nicht vorhanden
          mv package.zip sap-packages/${{ github.event.inputs.PACKAGEID }}.zip

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch --all
          git add sap-packages/
          git commit -m "Updated SAP CPI Package ZIP: ${{ github.event.inputs.PACKAGEID }}" || echo "No changes to commit"
          git push origin main  # Passe 'main' an deinen Branch an
      
          if git diff --cached --quiet; then
            echo "Keine Änderungen im Package"
          else
            git commit -m "chore: Update CPI package ${PACKAGE_ID} from $(date +'%Y-%m-%d %H:%M')"
            git push origin main
            echo "Package erfolgreich hochgeladen"
          fi
